sudo: required
language: generic
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/id_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker-compose up -d
after_success:
  - docker-compose push
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      repo: Khaalidsub/Lotus-blog-api
