sudo: required
language: generic
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_917f31f50c0f_key -iv $encrypted_917f31f50c0f_iv -in .travis/lotus-blogs.enc -out .travis/lotus-blogs -d
  - eval "$(ssh-agent -s)"
  - cp .travis/lotus-blogs ~/.ssh/lotus-blogs
  - chmod 600 ~/.ssh/lotus-blogs
  - ssh-add ~/.ssh/lotus-blogs
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker-compose -f docker-compose.dev.yml up -d --build
  - docker-compose push
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy.sh ./docker-compose.yml
    on:
      repo: Khaalidsub/Lotus-blog-api
