version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: "ts-ed-test/server:latest"
    container_name: blogs
    volumes:
      - /var/tools/public/images:/var/tools/public/images
      - /var/tools/public:/var/tools/public
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  mongo:
    image: "mongo:4.4"
    container_name: mongo
    restart: always
    volumes:
      - /data/db:/mongodat
    ports:
      - "27017:27017"
    command: [--auth]
