version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "khaalidsub/server:latest"
    container_name: blogs
    environment:
      - USER=lotus
      - PASS=tj.Vnp*J52w69r_g
      - DB=mongo
    volumes:
      - /var/tools/public/images:/var/tools/public/images
      - /var/tools/public:/var/tools/public
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  mongo:
    image: "mongo:4.4"
    container_name: mongo
    restart: always
    volumes:
      - /data/db
      - ./init-monog.js/:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lotus
      - MONGO_INITDB_ROOT_PASSWORD=tj.Vnp*J52w69r_g
      - MONGO_INITDB_DATABASE=blogs
    command: [--auth]
