version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "sleepinglotus/subaan-blogs-api"
    container_name: blogs
    environment:
      - USER=lotus
      - PASS=123
      - DB=mongodb
    volumes:
      - /var/tools/public/images:/var/tools/public/images
      - /var/tools/public:/var/tools/public
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  mongodb:
    image: "mongo:4.4"
    container_name: mongodb
    restart: always
    volumes:
      - /data/db
      - ./init-monog.js/:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lotus
      - MONGO_INITDB_ROOT_PASSWORD=123g
      - MONGO_INITDB_DATABASE=blogs
    command: [--auth]
