FROM node:12.13.0-alpine

RUN apk update && apk add build-base git python

WORKDIR /usr/app

COPY package.json .
COPY yarn.lock .
RUN yarn install --production
COPY ./src ./src
COPY ./dist ./dist




EXPOSE 8081

ENV PORT 8081
ENV NODE_ENV production
# ENV DEFAULT_URL mongodb://lotus:tj.Vnp*J52w69r_g@172.18.0.2:27017/blogs?authSource=admin
ENV IMAGEDIR=/var/tools/public/images


CMD ["yarn", "start:prod"]