version: "3.3"
services:
  web:
    image: "sleepinglotus/lotus-blogs-front"
    container_name: blogs-client
    environment:
      - SERVER=server
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    image: "sleepinglotus/subaan-blogs-api"
    container_name: blogs
    environment:
      - USER=lotus
      - PASS=tj.Vnp*J52w69r_g
      - DB=mongodb
    volumes:
      - /var/tools/public/images:/var/tools/public/images
      - /var/tools/public:/var/tools/public
    ports:
      - "8081:8081"
networks:
  default:
    external:
      name: blogs-api_default
